/*
 * Copyright (C) 2026 The Meshly Project Authors
 *
 * This file is part of Meshly, a decentralized peer-to-peer messenger
 * built on top of Tox (c-toxcore + ToxAV).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package org.meshly.app.data.repository

import android.content.Context
import android.content.SharedPreferences
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import org.meshly.app.daemontox.ToxBridge
import org.meshly.app.daemontox.fromHex
import org.meshly.app.data.model.Account

/**
 * Real c-toxcore-backed account repository. [org.meshly.app.MeshlyApplication.onCreate] already
 * starts the daemon ([ToxBridge.startDaemon]) unconditionally at process start (loading any
 * persisted savedata, or letting `tox_new` generate a fresh identity if none exists yet) - by the
 * time any of this class's methods run, a real `Tox`/`ToxAV` instance already exists either way.
 * This class's job is: persist the human-facing bits (nickname, bootstrap node list) that
 * `Tox_Options`/savedata don't cover on their own, and expose the resulting [Account] as a
 * [StateFlow] for the UI.
 */
class AccountRepository(private val context: Context) {
    private val prefs: SharedPreferences = context.getSharedPreferences("meshly_account", Context.MODE_PRIVATE)

    private val _currentAccount = MutableStateFlow<Account?>(null)
    val currentAccount: StateFlow<Account?> = _currentAccount.asStateFlow()

    /** True once onboarding has actually completed at least once on this device (savedata was persisted). */
    fun hasAccount(): Boolean = ToxSavedataStore.load(context) != null

    /**
     * Reads the identity the daemon already started with (see this class's doc), bootstraps the
     * DHT connection using the persisted (or default) node list, and publishes the resulting
     * [Account]. Safe to call whether or not [hasAccount] is true - the daemon's own identity
     * already exists regardless (freshly generated if this is a first run).
     */
    fun loadOrInitAccount(): Account {
        val nickname = prefs.getString(KEY_NICKNAME, null)
        val bootstrapNodes = loadPersistedBootstrapNodes() ?: DEFAULT_BOOTSTRAP_NODES
        bootstrapNodes.forEach(::bootstrapOne)
        bootstrapTcpRelays()

        val account = Account(
            toxId = ToxBridge.getSelfToxId(),
            nickname = nickname,
            bootstrapNodes = bootstrapNodes
        )
        _currentAccount.value = account
        return account
    }

    /**
     * Onboarding's "create a new account" step. The identity itself was already generated by
     * `tox_new` (no prior savedata) when the daemon started; this just attaches the chosen
     * nickname and persists savedata for the first time so the identity survives a restart.
     */
    fun createAccount(nickname: String?): Account {
        prefs.edit().putString(KEY_NICKNAME, nickname).apply()
        val account = loadOrInitAccount()
        ToxSavedataStore.persistNow(context)
        return account
    }

    /**
     * Logs out of the identity stored on this device. Without an exported backup, this identity
     * cannot be recovered afterwards - there is no server to fetch it back from, by design
     * (NFT-1). Clears every persisted preference (nickname, bootstrap nodes, savedata) so
     * [hasAccount] reports false and onboarding starts fresh; does NOT kill the running daemon
     * (a brand new identity is generated in-place the next time [loadOrInitAccount] runs, since
     * `tox_new` was already called with the now-forgotten savedata at process start - a full
     * identity swap without restarting the daemon isn't supported by this pass, so the app should
     * be relaunched after logout, which `MainScreen`'s logout flow already does via its full
     * back-stack-clearing navigation).
     */
    fun logout() {
        prefs.edit().clear().apply()
    }

    /** Adds a manual Tox DHT bootstrap node (FR-6.1): must be a `host:port:public-key` triple,
     *  matching c-toxcore's real bootstrap format; no-op if blank, malformed or already present. */
    fun addBootstrapNode(node: String) {
        val trimmed = node.trim()
        if (trimmed.isEmpty()) return
        val parts = trimmed.split(":")
        if (parts.size != 3 || parts.any { it.isBlank() }) return
        val current = currentAccount.value ?: return
        if (current.bootstrapNodes.contains(trimmed)) return
        val updated = current.bootstrapNodes + trimmed
        bootstrapOne(trimmed)
        persistBootstrapNodes(updated)
        _currentAccount.value = current.copy(bootstrapNodes = updated)
    }

    /**
     * Removes a bootstrap node, refusing to drop the last one - NFT-6 calls for at least one
     * node to survive at all times so the app never loses every entry point to the DHT. Tox has
     * no "un-bootstrap" call; this only stops the node from being re-bootstrapped on a future
     * daemon restart, it doesn't drop any already-established DHT connection through it.
     */
    fun removeBootstrapNode(node: String) {
        val current = currentAccount.value ?: return
        if (current.bootstrapNodes.size <= 1) return
        val updated = current.bootstrapNodes - node
        persistBootstrapNodes(updated)
        _currentAccount.value = current.copy(bootstrapNodes = updated)
    }

    private fun bootstrapOne(node: String) {
        val parts = node.trim().split(":")
        if (parts.size != 3) return
        val (host, portStr, pubkeyHex) = parts
        val port = portStr.toIntOrNull() ?: return
        runCatching { ToxBridge.bootstrap(host, port, pubkeyHex.fromHex()) }
    }

    /**
     * Registers this process's fixed set of TCP relays (see this class's top-of-file doc on why
     * UDP-only bootstrapping isn't enough) - separate from [bootstrapNodes]/[bootstrapOne], which
     * only cover UDP DHT bootstrap and are user-editable (FR-6.1). TCP relays are an
     * implementation-detail fallback path, not something the UI exposes for manual editing.
     */
    private fun bootstrapTcpRelays() {
        DEFAULT_TCP_RELAYS.forEach { node ->
            val parts = node.trim().split(":")
            if (parts.size != 3) return@forEach
            val (host, portStr, pubkeyHex) = parts
            val port = portStr.toIntOrNull() ?: return@forEach
            runCatching { ToxBridge.addTcpRelay(host, port, pubkeyHex.fromHex()) }
        }
    }

    private fun persistBootstrapNodes(nodes: List<String>) {
        prefs.edit().putString(KEY_BOOTSTRAP_NODES, nodes.joinToString(",")).apply()
    }

    private fun loadPersistedBootstrapNodes(): List<String>? =
        prefs.getString(KEY_BOOTSTRAP_NODES, null)?.split(",")?.filter { it.isNotBlank() }

    /**
     * Exports the real savedata (keys, friend list, name - everything `tox_get_savedata`
     * returns), base64-encoded and password-gated. NOTE: this is not yet encrypted with the
     * password the way `toxencryptsave`'s `tox_pass_encrypt` would (that JNI wrapper wasn't
     * written in this pass, see PHASE2_BUILD_TOX.md) - the password only gates whether
     * [importAccountBackup] accepts the bundle back, it doesn't protect the bytes at rest yet.
     * Real identity restore (the important part - this is not a fake string like the old mock's
     * export) works correctly regardless.
     */
    fun exportAccountBackup(password: String): String {
        if (ToxBridge.handle == null) return ""
        val savedataB64 = android.util.Base64.encodeToString(ToxBridge.getSavedata(), android.util.Base64.NO_WRAP)
        val nickname = currentAccount.value?.nickname.orEmpty()
        return "$BACKUP_PREFIX|$savedataB64|$nickname|${password.hashCode()}"
    }

    /**
     * Parses a bundle produced by [exportAccountBackup]; on a password match, tears down the
     * daemon this process already started (with the old or no identity) and restarts it with the
     * imported savedata in place ([ToxBridge.stopDaemon] + [ToxBridge.startDaemon] +
     * [ToxBridge.startAv] - a normal object-lifecycle operation, not a process restart). Returns
     * null on a malformed bundle or wrong password.
     */
    fun importAccountBackup(backupPayload: String, password: String): Account? {
        val parts = backupPayload.split("|")
        if (parts.size != 4 || parts[0] != BACKUP_PREFIX) return null

        val (_, savedataB64, nicknameRaw, passwordHash) = parts
        if (passwordHash.toIntOrNull() != password.hashCode()) return null
        val savedata = runCatching { android.util.Base64.decode(savedataB64, android.util.Base64.NO_WRAP) }
            .getOrNull() ?: return null
        if (savedata.isEmpty()) return null

        ToxBridge.stopDaemon()
        ToxBridge.startDaemon(savedata)
        ToxBridge.startAv()

        prefs.edit().putString(KEY_NICKNAME, nicknameRaw.ifEmpty { null }).apply()
        ToxSavedataStore.persistBytes(context, savedata)
        return loadOrInitAccount()
    }

    companion object {
        private const val BACKUP_PREFIX = "MESHLY_BACKUP_TOX_V1"
        private const val KEY_NICKNAME = "nickname"
        private const val KEY_BOOTSTRAP_NODES = "bootstrap_nodes"
        private val DEFAULT_BOOTSTRAP_NODES = Account(toxId = "").bootstrapNodes

        /**
         * host:tcp_port:pubkey triples for the same well-known public nodes as
         * [DEFAULT_BOOTSTRAP_NODES], but on each node's documented TCP relay port (443 preferred
         * where offered, since that's the port least likely to be filtered by a restrictive
         * network - the exact problem that motivated adding TCP relay support at all: a UDP-only
         * bootstrap looked "active" on a network that discards friend-rendezvous UDP traffic).
         */
        private val DEFAULT_TCP_RELAYS = listOf(
            "205.185.115.131:53:3091C6BEB2A993F1C6300C16549FABA67098FF3D62C6D253828B531470B53D68",
            "3.0.24.15:33445:E20ABCF38CDBFFD7D04B29C956B33F7B27A3BB7AF0618101617B036E4AEA402D",
            "tox2.mf-net.eu:3389:70EA214FDE161E7432530605213F18F7427DC773E276B3E317A07531F548545F",
            "tox3.mf-net.eu:3389:F4FC9398B7167668ED2BCF85634E04D4CDCDD2F95DA5F305BD234888B6E6A771",
            "tox4.mf-net.eu:3389:DCD342A0D5E2AA8E35C2BD2C7988F906EEB631B35100170A7F30E77D7F596442",
            "144.172.88.203:443:2016A0F2797EE3A8B004BA623F11AAFC8146F1B8F45107232A1A1AECCE856674",
            "119.59.101.63:443:197F746696062FA3BD07BB3BC0656ABD6692B4DAA27DACF0F474754F2B09B060",
            "172.86.77.39:443:AFFD3FAD3460E62A894E439534B27E5A5DCFE379C1C0FB78DEF1B150A87E900F",
            "144.217.167.73:3389:7E5668E0EE09E19F320AD47902419331FFEE147BB3606769CFBE921A2A2FD34C"
        )
    }
}
