/*
 * Copyright (C) 2026 The Meshly Project Authors
 *
 * This file is part of Meshly, a decentralized peer-to-peer messenger
 * built on top of GNU Jami's core engine (libjami).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// Phase 2 scaffolding for the real libjami native engine. See /PHASE2_BUILD.md
// before touching this file: building this module compiles jami-daemon's full
// contrib tree (OpenDHT, PJSIP, GnuTLS, FFmpeg, ...) from source per ABI, which
// realistically needs 30-50GB of disk and a couple of hours of CPU time.
//
// This module is intentionally NOT included in settings.gradle.kts yet, and
// :app does not depend on it, so the Phase 1 mock build (./gradlew assembleDebug)
// is completely unaffected by anything in here.

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

// Where jami-daemon's SWIG step will drop the generated net.jami.daemon.* Java
// sources (JamiServiceJNI, Callback, ConfigurationCallback, ...). Kept under
// build/ since it's fully regenerated by CMake on every native build.
val jamiJniPackageDir = layout.buildDirectory.dir("generated/jamiJni").get().asFile

android {
    namespace = "org.meshly.app.daemon"
    compileSdk = 35
    ndkVersion = "27.2.12479018"

    defaultConfig {
        minSdk = 24

        // Start with a single ABI while bringing the native build up; add the
        // others back once arm64-v8a is confirmed working end to end, since
        // BUILD_CONTRIB compiles every dependency again per ABI.
        ndk {
            abiFilters.add("arm64-v8a")
        }

        externalNativeBuild {
            cmake {
                // Mirrors the daemon's own documented Android/CMake invocation,
                // see native/upstream/jami-daemon/BUILD.md.
                arguments += listOf(
                    "-DJAMI_JNI=On",
                    "-DJAMI_JNI_PACKAGEDIR=${jamiJniPackageDir.absolutePath}",
                    "-DBUILD_CONTRIB=On",
                    "-DBUILD_EXTRA_TOOLS=On",
                    "-DJAMI_VIDEO=On",
                    "-DBUILD_SHARED_LIBS=Off"
                )
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("../native/upstream/jami-daemon/CMakeLists.txt")
            version = "3.22.1"
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    // The SWIG-generated net.jami.daemon.* facade (JamiServiceJNI, Callback,
    // ConfigurationCallback, ...) lands here after a real native build and is
    // compiled alongside RealJamiBridge.kt / JamiCallbackAdapter.kt.
    sourceSets {
        getByName("main") {
            java.srcDir(jamiJniPackageDir)
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.kotlinx.coroutines.android)
}
